# DEFAULT

# Thymeleaf properties 
spring:
  thymeleaf:
    cache: false

# Spring Actuator credentials
security:
  user:
    name: admin
    password: admin

# Overrideable port the application listens on
server:
  port: ${port:9000}

# EhCache configuration
ehcache:
  maxEntriesLocalHeap: 1000

# CORSFilter configuration
#cors:
#  allowOrigin: http://localhost:8080 http://127.0.0.1:8888
#  supportedHeaders: origin, content-type, accept, authorization, x-requested-with
 
---

# GEMFIRE

spring:
  profiles: gemfire
   
---
    
# SECURE

# To activate secure services
# edit the profile declared below

spring:
  profiles: secure
# profiles:
#   active: secure
    
# LoanService authentication credentials
loan:
  service:
    user: user
    password: password
    