# DEFAULT

# Thymeleaf properties 
spring:
  thymeleaf:
    cache: false

# Spring Actuator credentials
security:
  user:
    name: admin
    password: admin

# Overrideable port the application listens on
server:
  port: ${port:9000}

allowed:
  origins: http://localhost:8080, http://127.0.0.1:8888
  
---
    
# SECURE

# To activate secure services
# edit the profile declared below

spring:
  profiles: secure
# profiles:
#   active: secure
    
# LoanService authentication credentials
loan:
  service:
    user: user
    password: password